---
#- hosts: web
#  tasks:
#  - name: Unregister Red Hat subscription
#    redhat_subscription:
#      state: absent

- hosts: web
  tasks:
  - name: Cleanup rhsm
    shell: |
      sudo yum clean all
      sudo subscription-manager remove --all
      sudo subscription-manager unregister
      sudo subscription-manager clean
      exit

- hosts: web
  tasks:
  - name: rhsm force register with activation key
    redhat_subscription:
      state: absent
      activationkey: 'idm-lab-temp'
      org_id: '12451665'
      force_register: yes
